
workers_dev = true
name = "my-worker"
compatibility_date = "2025-03-11"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "your-database-name"
database_id = "your-database-id"
migrations_dir = "drizzle"
